services:
  podlet-web:
    build: .
    restart: unless-stopped
    environment:
      # These two can be omitted as they are the default setting
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 80
    ports:
      - "8080:80"
