services:
  podlet-web:
    build: .
    restart: unless-stopped
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 80
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
